import type { Metadata } from "next";
import "./reset.scss";
import Category from "../components/category";
import Slider from "../components/slider";
import Contents from "../components/contents";
import SwipeNavigator from "@/components/common/SwipleNavigator";

export const metadata: Metadata = {
  title: "Hanteo Global Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SwipeNavigator>
          <Category />
          {children}
          <Slider />
          <Contents />
        </SwipeNavigator>
      </body>
    </html>
  );
}
